//! Project documentation generated from what the run actually did (task 0013).
//!
//! Every document here is rendered deterministically from task state — the
//! audit history, acceptance criteria, verification results and the frozen
//! agent selection — plus a few file-existence checks in the finished project.
//! Nothing is asked of a model, so nothing can be invented: a command appears
//! only if this run executed it, a decision only if it was recorded, and a
//! timestamp only if it came from the audit log.
//!
//! Documentation the run did not write is never overwritten. When a target
//! path already holds something else, the generated document is written beside
//! it instead and the original is reported as preserved.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::acceptance::CriterionStatus;
use crate::task::{Task, TaskEvent, TaskStatus};
use crate::technology::{BuildTool, ProjectProfile, TechStack};
use crate::verification::VerificationResult;

/// Marks a file as ours, so a later run may replace it and nothing else is.
pub const MARKER: &str = "<!-- generated by multiagent-chat";

/// The documents task 0013 requires, in the order they are written.
pub const DOCUMENTS: [&str; 6] = [
    "README.md",
    "docs/ARCHITECTURE.md",
    "docs/DEVELOPMENT_LOG.md",
    "docs/DECISIONS.md",
    "docs/AI_USAGE.md",
    "docs/NEXT_STEPS.md",
];

/// What one generation produced. Paths are project-relative, never absolute:
/// an internal workspace path must not reach an event, a report or a document.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Submission {
    /// Documents written, in project-relative form.
    pub written: Vec<String>,
    /// Existing documents left exactly as they were.
    pub preserved: Vec<String>,
}

/// Everything the documents are rendered from.
pub struct SubmissionInputs<'a> {
    /// A REDACTED task snapshot; see `TaskManager::evidence_snapshot`.
    pub task: &'a Task,
    pub profile: &'a ProjectProfile,
    /// Every verification command this run actually executed.
    pub verification: &'a [VerificationResult],
    /// The finished project, inspected only for which files exist.
    pub project: &'a Path,
}

/// Render all six documents. Pure: it reads task state and file existence only.
pub fn documents(inputs: &SubmissionInputs<'_>) -> Vec<(&'static str, String)> {
    let rendered = vec![
        ("README.md", readme(inputs)),
        ("docs/ARCHITECTURE.md", architecture(inputs)),
        (
            "docs/DEVELOPMENT_LOG.md",
            header(inputs.task) + &crate::evidence::development_log(inputs.task),
        ),
        (
            "docs/DECISIONS.md",
            header(inputs.task) + &crate::evidence::decisions(inputs.task),
        ),
        (
            "docs/AI_USAGE.md",
            header(inputs.task) + &crate::evidence::agent_usage(inputs.task),
        ),
        ("docs/NEXT_STEPS.md", next_steps(inputs)),
    ];
    debug_assert_eq!(
        rendered.iter().map(|(name, _)| *name).collect::<Vec<_>>(),
        DOCUMENTS,
        "every required document must be rendered, in order"
    );
    rendered
}

/// Write the documents into the finished project.
///
/// A path that already holds a file this run did not generate is preserved and
/// the document goes to `<name>.generated.md` beside it, so existing
/// documentation is never destroyed and nothing is silently dropped.
pub fn write_into(project: &Path, documents: &[(&'static str, String)]) -> Result<Submission> {
    let mut submission = Submission::default();
    for (name, contents) in documents {
        let target = project.join(name);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("could not create the documentation folder for {name}"))?;
        }
        let (path, preserved) = destination(&target, name)?;
        write_document(&path, contents)
            .with_context(|| format!("could not write generated documentation {name}"))?;
        if let Some(preserved) = preserved {
            submission.preserved.push(preserved);
        }
        submission.written.push(relative(project, &path));
    }
    Ok(submission)
}

/// Where a document may go, and what was preserved to keep it safe.
fn destination(target: &Path, name: &str) -> Result<(PathBuf, Option<String>)> {
    match fs::symlink_metadata(target) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok((target.into(), None)),
        Err(error) => Err(error).with_context(|| format!("could not inspect {name}")),
        Ok(metadata) => {
            // A link is never followed and never replaced.
            if !crate::repository_file::is_link(&metadata)
                && metadata.is_file()
                && fs::read_to_string(target).is_ok_and(|existing| existing.starts_with(MARKER))
            {
                // Ours from an earlier run: replacing it destroys nothing.
                return Ok((target.into(), None));
            }
            let stem = target
                .file_stem()
                .and_then(|stem| stem.to_str())
                .ok_or_else(|| anyhow::anyhow!("unsupported documentation name {name}"))?;
            Ok((
                target.with_file_name(format!("{stem}.generated.md")),
                Some(name.to_string()),
            ))
        }
    }
}

/// Replace by rename, so an existing directory entry is never opened.
fn write_document(path: &Path, contents: &str) -> Result<()> {
    if let Ok(metadata) = fs::symlink_metadata(path)
        && (crate::repository_file::is_link(&metadata) || !metadata.is_file())
    {
        bail!("refusing to replace a linked or non-regular documentation file");
    }
    let parent = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("documentation path has no parent"))?;
    let temporary = parent.join(format!(".docs-{}.tmp", uuid::Uuid::new_v4()));
    let result = fs::write(&temporary, contents).and_then(|()| fs::rename(&temporary, path));
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    Ok(result?)
}

fn relative(project: &Path, path: &Path) -> String {
    path.strip_prefix(project)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------

fn header(task: &Task) -> String {
    format!(
        "{MARKER} for task {} — regenerate rather than editing in place -->\n\n",
        task.id
    )
}

fn readme(inputs: &SubmissionInputs<'_>) -> String {
    let task = inputs.task;
    let mut markdown = header(task);
    markdown.push_str(&format!("# {}\n\n", one_line(&task.title)));
    markdown.push_str("## Purpose\n\n");
    markdown.push_str(&quote(&task.description));
    markdown.push_str("\n\n## Architecture summary\n\n");
    markdown.push_str(&match spec_section(task, "Architecture") {
        Some(section) => summarize(&section),
        None => "The approved specification recorded no architecture section.".into(),
    });
    markdown.push_str("\n\n## Prerequisites\n\n");
    for prerequisite in prerequisites(inputs.profile) {
        markdown.push_str(&format!("- {prerequisite}\n"));
    }
    markdown.push_str(
        "\n## Running it locally\n\n\
         This project was built and checked in an isolated workspace. Only the commands \
         listed under **Verified commands** were executed there; no other start, build or \
         deployment command has been verified by this run.\n\n",
    );

    let configuration = present_files(inputs.project, &[".env.example", ".env.sample", ".env"]);
    markdown.push_str("## Configuration\n\n");
    if configuration.is_empty() {
        markdown.push_str("No configuration template was detected in the project.\n\n");
    } else {
        markdown.push_str("The project defines:\n\n");
        for file in &configuration {
            markdown.push_str(&format!("- `{file}`\n"));
        }
        markdown.push('\n');
    }

    let migrations = present_files(
        inputs.project,
        &[
            "migrations",
            "db/migrate",
            "alembic.ini",
            "prisma/schema.prisma",
        ],
    );
    if !migrations.is_empty() {
        markdown.push_str("## Database setup\n\n");
        markdown.push_str("The project defines database assets:\n\n");
        for file in &migrations {
            markdown.push_str(&format!("- `{file}`\n"));
        }
        markdown.push_str("\nNo migration command was executed by this run.\n\n");
    }

    let containers = present_files(
        inputs.project,
        &[
            "Dockerfile",
            "docker-compose.yml",
            "docker-compose.yaml",
            "compose.yaml",
        ],
    );
    if !containers.is_empty() {
        markdown.push_str("## Containers\n\n");
        for file in &containers {
            markdown.push_str(&format!("- `{file}`\n"));
        }
        markdown.push_str("\nNo container build or start command was executed by this run.\n\n");
    }

    markdown.push_str("## Verified commands\n\n");
    if inputs.verification.is_empty() {
        markdown.push_str(
            "This run detected no automatic verification command for the project, so no build \
             or test command is claimed to work here.\n\n",
        );
    } else {
        markdown.push_str("| Command | Result |\n| --- | --- |\n");
        for result in inputs.verification {
            markdown.push_str(&format!(
                "| `{}` | {} |\n",
                one_line(&result.command),
                if result.success { "passed" } else { "FAILED" }
            ));
        }
        markdown.push('\n');
    }

    markdown.push_str("## Current status\n\n");
    markdown.push_str(&status_lines(task));
    markdown.push_str("\n## Known limitations\n\n");
    let limitations = limitations(task);
    if limitations.is_empty() {
        markdown.push_str("No limitation was recorded by this run.\n");
    } else {
        for limitation in limitations {
            markdown.push_str(&format!("- {limitation}\n"));
        }
    }
    markdown
}

fn architecture(inputs: &SubmissionInputs<'_>) -> String {
    let task = inputs.task;
    let mut markdown = header(task);
    markdown.push_str("# Architecture\n\n## Technology\n\n");
    markdown.push_str(&format!("- Stack: {}\n", stack_name(&inputs.profile.stack)));
    markdown.push_str(&format!(
        "- Build tool: {}\n",
        build_tool_name(&inputs.profile.build_tool)
    ));
    if let Some(framework) = &inputs.profile.framework {
        markdown.push_str(&format!("- Framework: {}\n", one_line(framework)));
    }
    if !inputs.profile.evidence.is_empty() {
        markdown.push_str(&format!(
            "- Detected from: {}\n",
            inputs
                .profile
                .evidence
                .iter()
                .map(|evidence| format!("`{}`", one_line(evidence)))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    for (heading, section) in [
        ("Approved architecture", "Architecture"),
        ("Agreed solution", "Agreed solution"),
    ] {
        markdown.push_str(&format!("\n## {heading}\n\n"));
        markdown.push_str(&match spec_section(task, section) {
            Some(body) => body,
            None => format!("The approved specification recorded no {section} section."),
        });
        markdown.push('\n');
    }

    markdown.push_str("\n## Implemented components\n\n");
    if task.milestones.is_empty() {
        markdown.push_str("No milestone plan was recorded.\n");
    } else {
        for milestone in &task.milestones {
            markdown.push_str(&format!(
                "- **{}. {}** — {} ({})\n",
                milestone.order,
                one_line(&milestone.title),
                one_line(&milestone.objective),
                milestone.status.label()
            ));
            if let Some(commit) = &milestone.commit {
                markdown.push_str(&format!("  - Commit `{}`\n", one_line(&commit.short_sha)));
            }
            if !milestone.criteria.is_empty() {
                markdown.push_str(&format!(
                    "  - Acceptance criteria: {}\n",
                    milestone.criteria.join(", ")
                ));
            }
        }
    }

    markdown.push_str("\n## Recorded risks and constraints\n\n");
    markdown.push_str(&match spec_section(task, "Open risks") {
        Some(body) => body,
        None => "The approved specification recorded no open risks.".into(),
    });
    markdown.push('\n');
    markdown
}

fn next_steps(inputs: &SubmissionInputs<'_>) -> String {
    let task = inputs.task;
    let mut markdown = header(task);
    markdown.push_str("# Next steps\n\n## Required but incomplete\n\n");

    let outstanding = task
        .acceptance
        .iter()
        .filter(|criterion| criterion.status.is_outstanding())
        .collect::<Vec<_>>();
    let mut required = Vec::new();
    for criterion in &outstanding {
        required.push(format!(
            "`{}` [{}] {}{}",
            criterion.id,
            criterion.status.label(),
            one_line(&criterion.description),
            if criterion.milestones.is_empty() {
                " (no milestone in this run was responsible for it)".to_string()
            } else {
                String::new()
            }
        ));
        for finding in &criterion.blocking_findings {
            required.push(format!("  - Unresolved finding: {}", one_line(finding)));
        }
    }
    for milestone in &task.milestones {
        if let Some(review) = &milestone.review
            && !review.status.is_pass()
        {
            required.push(format!(
                "Milestone {} did not pass implementation review ({})",
                milestone.order,
                review.summary()
            ));
        }
    }
    for result in inputs.verification.iter().filter(|result| !result.success) {
        required.push(format!(
            "Verification command `{}` failed",
            one_line(&result.command)
        ));
    }
    if required.is_empty() {
        markdown.push_str("Nothing required by the approved specification is outstanding.\n");
    } else {
        for item in required {
            markdown.push_str(&format!("- {item}\n"));
        }
    }

    markdown.push_str("\n## Deferred work\n\n");
    let deferred = task
        .acceptance
        .iter()
        .filter(|criterion| criterion.status == CriterionStatus::Deferred)
        .collect::<Vec<_>>();
    if deferred.is_empty() {
        markdown.push_str("No requirement was deferred.\n");
    } else {
        for criterion in deferred {
            markdown.push_str(&format!(
                "- `{}` {}\n",
                criterion.id,
                one_line(&criterion.description)
            ));
        }
    }

    markdown.push_str("\n## Optional future improvements\n\n");
    markdown.push_str(
        "Recorded by the approved specification as out of scope; none of it was implemented \
         or verified by this run.\n\n",
    );
    markdown.push_str(&match spec_section(task, "Out of scope") {
        Some(body) => body,
        None => "The approved specification recorded nothing as out of scope.".into(),
    });
    markdown.push('\n');
    markdown
}

// ---------------------------------------------------------------------------
// Shared rendering
// ---------------------------------------------------------------------------

/// The run's own status, stated plainly enough that an incomplete task cannot
/// read as a finished one.
fn status_lines(task: &Task) -> String {
    let passed = task
        .acceptance
        .iter()
        .filter(|criterion| criterion.status == CriterionStatus::Passed)
        .count();
    let mut lines = format!(
        "- Task status: **{}**\n",
        match task.status {
            TaskStatus::Completed => "completed",
            TaskStatus::Failed => "failed",
            TaskStatus::Cancelled => "cancelled",
            TaskStatus::Rejected => "rejected",
            _ => "in progress",
        }
    );
    if task.acceptance.is_empty() {
        lines.push_str("- No acceptance criteria were generated for this run.\n");
    } else {
        lines.push_str(&format!(
            "- Acceptance criteria: **{passed} of {} passed**\n",
            task.acceptance.len()
        ));
        let outstanding = task
            .acceptance
            .iter()
            .filter(|criterion| criterion.status.is_outstanding())
            .map(|criterion| criterion.id.as_str())
            .collect::<Vec<_>>();
        if !outstanding.is_empty() {
            lines.push_str(&format!(
                "- Outstanding criteria: {} — see `docs/NEXT_STEPS.md`\n",
                outstanding.join(", ")
            ));
        }
    }
    if let Some(error) = &task.error {
        lines.push_str(&format!("- Recorded error: {}\n", one_line(error)));
    }
    if task.status != TaskStatus::Completed
        || task
            .acceptance
            .iter()
            .any(|criterion| criterion.status.is_outstanding())
    {
        lines.push_str(
            "- This project is **not** complete: the items above were not satisfied by this run.\n",
        );
    }
    lines
}

fn limitations(task: &Task) -> Vec<String> {
    let mut limitations = Vec::new();
    for criterion in &task.acceptance {
        if criterion.status.is_outstanding() {
            limitations.push(format!(
                "`{}` is {} — {}",
                criterion.id,
                criterion.status.label(),
                one_line(&criterion.description)
            ));
        }
    }
    for milestone in &task.milestones {
        if let Some(review) = &milestone.review {
            for finding in &review.findings {
                limitations.push(format!(
                    "Unresolved review finding: {}",
                    one_line(&finding.requirement)
                ));
            }
        }
    }
    if let Some(error) = &task.error {
        limitations.push(one_line(error));
    }
    limitations
}

/// The approved specification's own words for one section.
fn spec_section(task: &Task, name: &str) -> Option<String> {
    let specification = task.spec.as_deref()?;
    let body = crate::evidence::markdown_section(specification, name)?;
    (!body.trim().is_empty()).then(|| body.trim().to_string())
}

/// The first paragraph, which is enough for a summary.
fn summarize(section: &str) -> String {
    section
        .split("\n\n")
        .next()
        .unwrap_or(section)
        .trim()
        .to_string()
}

fn prerequisites(profile: &ProjectProfile) -> Vec<String> {
    let mut prerequisites = match profile.stack {
        TechStack::Rust => vec!["A stable Rust toolchain (`cargo`)".to_string()],
        TechStack::JavaSpringBoot => vec!["A JDK".to_string()],
        TechStack::Python => vec!["A Python 3 interpreter".to_string()],
        TechStack::TypeScriptNode => vec!["Node.js and npm".to_string()],
        TechStack::Custom => vec![
            "The toolchain this project's build files require; none was detected automatically"
                .to_string(),
        ],
    };
    match profile.build_tool {
        BuildTool::Maven => prerequisites.push("Maven, or the repository's `mvnw` wrapper".into()),
        BuildTool::Gradle => {
            prerequisites.push("Gradle, or the repository's `gradlew` wrapper".into())
        }
        _ => {}
    }
    prerequisites.push("Git".into());
    prerequisites
}

fn stack_name(stack: &TechStack) -> &'static str {
    match stack {
        TechStack::Rust => "Rust",
        TechStack::JavaSpringBoot => "Java / Spring Boot",
        TechStack::Python => "Python",
        TechStack::TypeScriptNode => "TypeScript / Node.js",
        TechStack::Custom => "Custom / other",
    }
}

fn build_tool_name(tool: &BuildTool) -> &'static str {
    match tool {
        BuildTool::Cargo => "Cargo",
        BuildTool::Maven => "Maven",
        BuildTool::Gradle => "Gradle",
        BuildTool::Npm => "npm",
        BuildTool::Python => "Python tooling",
        BuildTool::Custom => "not detected",
    }
}

/// Which of these project-relative paths exist, so a document mentions only
/// what the finished project really contains.
fn present_files(project: &Path, candidates: &[&str]) -> Vec<String> {
    candidates
        .iter()
        .filter(|candidate| {
            fs::symlink_metadata(project.join(candidate))
                .is_ok_and(|metadata| !crate::repository_file::is_link(&metadata))
        })
        .map(|candidate| (*candidate).to_string())
        .collect()
}

fn one_line(value: &str) -> String {
    value.replace(['\r', '\n'], " ").trim().to_string()
}

fn quote(value: &str) -> String {
    let value = value.trim();
    if value.is_empty() {
        "No description was recorded.".to_string()
    } else {
        value.to_string()
    }
}

/// The audit line for a completed generation.
pub fn generated_event(submission: &Submission) -> TaskEvent {
    TaskEvent::SubmissionDocumentationGenerated {
        written: submission.written.clone(),
        preserved: submission.preserved.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::acceptance::CriterionEvidence;
    use crate::agent::{
        AgentSelection, ChatAgentConfig, ChatProvider, CodingAgentConfig, CodingTool,
    };
    use crate::execution_limits::HistoryLimits;
    use crate::task::{AgentStage, TaskManager};
    use crate::technology::TechStack;

    const SPEC: &str = "## Problem\nEvents need managing.\n\n         ## Agreed solution\nOne service with a queue.\n\n         ## Architecture\nAn axum service backed by Postgres.\n\nA worker drains the queue.\n\n         ## Steps\n1. Create events\n2. Deliver reminders\n\n         ## Out of scope\nMobile clients.\n\n         ## Open risks\nQueue ordering under load.";

    fn selection() -> AgentSelection {
        AgentSelection {
            proposer: ChatAgentConfig::new(ChatProvider::Gemini, "frozen-proposer-model"),
            critic: ChatAgentConfig::new(ChatProvider::Anthropic, "frozen-critic-model"),
            worker: CodingAgentConfig::new(CodingTool::ClaudeCode, "frozen-worker-model"),
        }
    }

    /// A finished run: two milestones, criteria, verification and a secret that
    /// the established redaction must keep out of every document.
    fn finished_task(secret: &str) -> Task {
        let manager = TaskManager::with_history_limits_and_secrets(
            HistoryLimits::default(),
            [secret.to_string()],
        );
        let task = manager
            .create_from_request(
                crate::task::TaskRequest {
                    kind: crate::task::TaskKind::NewProject,
                    title: "Event service".into(),
                    description: "Manage events and remind attendees.".into(),
                    project_id: None,
                    technology: Some(TechStack::Rust),
                    output: Some(crate::task::OutputTarget::ReviewableResult),
                    destination: None,
                    agents: None,
                    git_mode: None,
                },
                selection(),
            )
            .unwrap();
        let emitter = manager.emitter(task.id);
        emitter.emit(TaskEvent::TaskStarted);
        emitter.emit(TaskEvent::AgentsSelected {
            agents: selection(),
        });
        emitter.emit(TaskEvent::Critique {
            round: 1,
            text: "REASON: queue ordering unproven\nVERDICT: NEEDS_WORK".into(),
            verdict: Some("needs_work".into()),
            reason: Some("queue ordering unproven".into()),
        });
        emitter.emit(TaskEvent::Spec {
            markdown: SPEC.into(),
            path: "artifacts/approved-spec.md".into(),
        });
        emitter.status(crate::task::TaskStatus::WaitingForApproval);
        manager
            .decide_checked(
                task.id,
                crate::task::Decision {
                    approve: true,
                    spec: None,
                },
            )
            .unwrap();
        let mut milestones = crate::milestone::plan_from_spec(SPEC, &[]).unwrap();
        let criteria = crate::acceptance::plan(SPEC, &mut milestones).unwrap();
        emitter.emit(TaskEvent::MilestonePlanCreated {
            milestones: milestones.clone(),
        });
        emitter.emit(TaskEvent::AcceptanceCriteriaGenerated { criteria });
        emitter.record_evidence(crate::evidence::EvidencePayload::AgentInteraction {
            stage: AgentStage::Debate,
            role: crate::evidence::EvidenceRole::Proposer,
            round: Some(1),
            provider: ChatProvider::Gemini,
            model: "frozen-proposer-model".into(),
            prompt: format!("design it with API key {secret}"),
            response: Some("a design".into()),
            status: crate::evidence::EvidenceStatus::Completed,
            error: None,
            duration_ms: 12,
            truncated: false,
        });
        for milestone in &milestones {
            emitter.emit(TaskEvent::MilestoneStarted {
                id: milestone.id.clone(),
                order: milestone.order,
                title: milestone.title.clone(),
                worker_tool: CodingTool::ClaudeCode,
                worker_model: "frozen-worker-model".into(),
            });
            emitter.emit(TaskEvent::MilestoneCompleted {
                id: milestone.id.clone(),
                order: milestone.order,
                title: milestone.title.clone(),
                verification: verification(),
                worker_result_summary: "Worker completed successfully.".into(),
            });
        }
        emitter.emit(TaskEvent::AcceptanceCriterionUpdated {
            id: "AC-001".into(),
            status: CriterionStatus::Passed,
            evidence: Some(CriterionEvidence::automatic_verification(
                "milestone m1: 1 verification command(s) passed: cargo test",
            )),
            blocking_finding: None,
            findings_cleared: false,
        });
        emitter.emit(TaskEvent::TaskCompleted);
        manager.evidence_snapshot(task.id).unwrap()
    }

    fn verification() -> Vec<VerificationResult> {
        vec![VerificationResult {
            command: "cargo test".into(),
            success: true,
            output: "ok".into(),
        }]
    }

    fn project(tag: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "mac-submission-{tag}-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4()
        ));
        fs::create_dir_all(&root).unwrap();
        root
    }

    fn generate(task: &Task, root: &Path, verification: &[VerificationResult]) -> Submission {
        let documents = documents(&SubmissionInputs {
            task,
            profile: &ProjectProfile::selected(TechStack::Rust),
            verification,
            project: root,
        });
        write_into(root, &documents).unwrap()
    }

    fn read(root: &Path, name: &str) -> String {
        fs::read_to_string(root.join(name)).unwrap()
    }

    /// Required test 1: every document is generated for a successful task, from
    /// what the run actually recorded.
    #[test]
    fn a_successful_task_produces_every_document() {
        let root = project("success");
        let task = finished_task("unused-secret-value");

        let submission = generate(&task, &root, &verification());

        assert_eq!(submission.written, DOCUMENTS, "all six, in order");
        assert!(submission.preserved.is_empty());
        let readme = read(&root, "README.md");
        assert!(readme.starts_with(MARKER), "{readme}");
        assert!(readme.contains("# Event service"), "{readme}");
        assert!(
            readme.contains("Manage events and remind attendees."),
            "{readme}"
        );
        assert!(
            readme.contains("An axum service backed by Postgres."),
            "{readme}"
        );
        assert!(readme.contains("A stable Rust toolchain"), "{readme}");
        assert!(readme.contains("| `cargo test` | passed |"), "{readme}");
        assert!(readme.contains("Task status: **completed**"), "{readme}");
        // A command the run never executed is never claimed to work.
        assert!(!readme.contains("cargo run"), "{readme}");
        assert!(!readme.contains("docker compose up"), "{readme}");

        let architecture = read(&root, "docs/ARCHITECTURE.md");
        assert!(architecture.contains("Stack: Rust"), "{architecture}");
        assert!(
            architecture.contains("A worker drains the queue."),
            "{architecture}"
        );
        assert!(
            architecture.contains("One service with a queue."),
            "{architecture}"
        );
        assert!(
            architecture.contains("**1. Create events**"),
            "{architecture}"
        );
        assert!(
            architecture.contains("Queue ordering under load."),
            "{architecture}"
        );

        let decisions = read(&root, "docs/DECISIONS.md");
        assert!(decisions.contains("queue ordering unproven"), "{decisions}");
        fs::remove_dir_all(root).ok();
    }

    /// Required test 2 and 4: an incomplete run is documented as incomplete,
    /// and what is missing reaches the status and the next steps.
    #[test]
    fn an_incomplete_task_is_documented_honestly() {
        let root = project("incomplete");
        let mut task = finished_task("unused-secret-value");
        task.status = TaskStatus::Failed;
        task.error = Some("one or more verification commands failed".into());
        task.acceptance[1].status = CriterionStatus::Failed;
        task.acceptance[1]
            .blocking_findings
            .push("[blocker] AC-002: reminders never fire".into());
        let failed = vec![VerificationResult {
            command: "cargo test".into(),
            success: false,
            output: "1 failed".into(),
        }];

        generate(&task, &root, &failed);

        let readme = read(&root, "README.md");
        assert!(readme.contains("Task status: **failed**"), "{readme}");
        assert!(readme.contains("| `cargo test` | FAILED |"), "{readme}");
        assert!(readme.contains("Outstanding criteria: AC-002"), "{readme}");
        assert!(
            readme.contains("This project is **not** complete"),
            "{readme}"
        );
        assert!(readme.contains("`AC-002` is FAILED"), "{readme}");

        let next = read(&root, "docs/NEXT_STEPS.md");
        assert!(next.contains("## Required but incomplete"), "{next}");
        assert!(next.contains("`AC-002` [FAILED]"), "{next}");
        assert!(next.contains("reminders never fire"), "{next}");
        assert!(
            next.contains("Verification command `cargo test` failed"),
            "{next}"
        );
        // Optional work stays separate from what the specification required.
        let optional = next
            .split("## Optional future improvements")
            .nth(1)
            .unwrap();
        assert!(optional.contains("Mobile clients."), "{optional}");
        assert!(!optional.contains("AC-002"), "{optional}");
        fs::remove_dir_all(root).ok();
    }

    /// Required test 3: the frozen agent configuration, not current defaults.
    #[test]
    fn ai_usage_reports_the_frozen_agents() {
        let root = project("agents");
        let task = finished_task("unused-secret-value");

        generate(&task, &root, &verification());

        let usage = read(&root, "docs/AI_USAGE.md");
        assert!(usage.contains("frozen-proposer-model"), "{usage}");
        assert!(usage.contains("frozen-critic-model"), "{usage}");
        assert!(usage.contains("frozen-worker-model"), "{usage}");
        assert!(usage.contains("Gemini"), "{usage}");
        assert!(usage.contains("Anthropic"), "{usage}");
        assert!(usage.contains("Claude Code"), "{usage}");
        assert!(usage.contains("Purpose:"), "{usage}");
        fs::remove_dir_all(root).ok();
    }

    /// Required test 5: documentation the run did not write is never destroyed.
    #[test]
    fn existing_documentation_is_preserved() {
        let root = project("preserve");
        let task = finished_task("unused-secret-value");
        fs::create_dir_all(root.join("docs")).unwrap();
        fs::write(root.join("README.md"), "# Hand-written\n\nKeep me.\n").unwrap();
        fs::write(
            root.join("docs/ARCHITECTURE.md"),
            "# Hand-written architecture\n",
        )
        .unwrap();

        let submission = generate(&task, &root, &verification());

        assert_eq!(
            fs::read_to_string(root.join("README.md")).unwrap(),
            "# Hand-written\n\nKeep me.\n",
            "an existing README is never overwritten"
        );
        assert_eq!(
            fs::read_to_string(root.join("docs/ARCHITECTURE.md")).unwrap(),
            "# Hand-written architecture\n"
        );
        assert_eq!(
            submission.preserved,
            vec!["README.md".to_string(), "docs/ARCHITECTURE.md".to_string()]
        );
        assert!(
            submission
                .written
                .contains(&"README.generated.md".to_string())
        );
        assert!(
            submission
                .written
                .contains(&"docs/ARCHITECTURE.generated.md".to_string())
        );
        assert!(read(&root, "README.generated.md").contains("# Event service"));

        // A second run replaces only what the first run generated.
        let submission = generate(&task, &root, &verification());
        assert_eq!(submission.preserved.len(), 2);
        assert_eq!(
            fs::read_to_string(root.join("README.md")).unwrap(),
            "# Hand-written\n\nKeep me.\n"
        );
        assert!(read(&root, "docs/NEXT_STEPS.md").starts_with(MARKER));
        fs::remove_dir_all(root).ok();
    }

    /// Required test 6: the established redaction covers generated documents.
    #[test]
    fn secrets_never_reach_generated_documentation() {
        let root = project("secrets");
        let secret = "super-secret-provider-key";
        let task = finished_task(secret);

        let submission = generate(&task, &root, &verification());

        for document in &submission.written {
            let contents = read(&root, document);
            assert!(!contents.contains(secret), "{document} leaked the secret");
            assert!(!contents.contains("sk-"), "{document} leaked a token shape");
        }
        // The prompt that carried it is still represented, with the value gone.
        assert!(read(&root, "docs/DEVELOPMENT_LOG.md").contains("Proposer interaction completed"));
        fs::remove_dir_all(root).ok();
    }

    /// Required test 7: the development log uses the recorded timestamps.
    #[test]
    fn the_development_log_uses_recorded_timestamps() {
        let root = project("timestamps");
        let task = finished_task("unused-secret-value");
        let recorded = task
            .history
            .iter()
            .map(|event| {
                event
                    .timestamp
                    .to_rfc3339_opts(chrono::SecondsFormat::Millis, true)
            })
            .collect::<Vec<_>>();

        generate(&task, &root, &verification());

        let log = read(&root, "docs/DEVELOPMENT_LOG.md");
        for timestamp in &recorded {
            assert!(log.contains(timestamp), "{timestamp} missing from the log");
        }
        assert!(log.contains("Sequence: 1"), "{log}");
        // Nothing invents a time of its own.
        let stamps = log.matches("T").count();
        assert!(stamps >= recorded.len(), "{log}");
        fs::remove_dir_all(root).ok();
    }

    /// A project that defines containers or configuration says so, and one that
    /// does not stays silent rather than inventing instructions.
    #[test]
    fn only_files_the_project_really_has_are_documented() {
        let root = project("markers");
        let task = finished_task("unused-secret-value");
        fs::write(root.join("docker-compose.yml"), "services:\n").unwrap();
        fs::write(root.join(".env.example"), "PORT=3000\n").unwrap();

        generate(&task, &root, &verification());
        let readme = read(&root, "README.md");
        assert!(readme.contains("## Containers"), "{readme}");
        assert!(readme.contains("`docker-compose.yml`"), "{readme}");
        assert!(readme.contains("`.env.example`"), "{readme}");
        assert!(!readme.contains("## Database setup"), "{readme}");

        let bare = project("markers-bare");
        generate(&task, &bare, &verification());
        let readme = read(&bare, "README.md");
        assert!(!readme.contains("## Containers"), "{readme}");
        assert!(
            readme.contains("No configuration template was detected"),
            "{readme}"
        );
        fs::remove_dir_all(root).ok();
        fs::remove_dir_all(bare).ok();
    }

    /// A run with no automatic verification must not imply that tests exist.
    #[test]
    fn a_project_without_verification_claims_no_commands() {
        let root = project("no-verification");
        let task = finished_task("unused-secret-value");

        generate(&task, &root, &[]);

        let readme = read(&root, "README.md");
        assert!(
            readme.contains("detected no automatic verification command"),
            "{readme}"
        );
        assert!(!readme.contains("| Command | Result |"), "{readme}");
        fs::remove_dir_all(root).ok();
    }
}
